//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sift.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sift.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap erase {
            get {
                object obj = ResourceManager.GetObject("erase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Use (Only folder structure ignore) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fc_ignore {
            get {
                return ResourceManager.GetString("fc_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fc_notuse {
            get {
                return ResourceManager.GetString("fc_notuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fc_use {
            get {
                return ResourceManager.GetString("fc_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap input {
            get {
                object obj = ResourceManager.GetObject("input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {0,8:#,0} files copied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string messagebox1 {
            get {
                return ResourceManager.GetString("messagebox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Over {0:#,0} files.{1}Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string messagebox2 {
            get {
                return ResourceManager.GetString("messagebox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:#,0} / {1:#,0} files processed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string messagebox3 {
            get {
                return ResourceManager.GetString("messagebox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t run multiple instances. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string messagebox4 {
            get {
                return ResourceManager.GetString("messagebox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:#,0} lines over than target files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string messagebox5 {
            get {
                return ResourceManager.GetString("messagebox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:#,0} lines less than target files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string messagebox6 {
            get {
                return ResourceManager.GetString("messagebox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:#,0} files processed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string messagebox7 {
            get {
                return ResourceManager.GetString("messagebox7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FastCopy.exe Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notfound {
            get {
                return ResourceManager.GetString("notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap signature {
            get {
                object obj = ResourceManager.GetObject("signature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
